# Generated by Django 2.2.16 on 2022-06-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220605_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
